apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  labels:
    app: website-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  website-deployment
  template:
    metadata:
      labels:
        app:  website-deployment
    spec:
      containers:
      - name:  website-deployment
        image: akashdevops03/website-deployment
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: website-deployment-service
spec:
  type: NodePort
  selector:
    app: website-deployment
  ports:
  - protocol: TCP
    port: 80            # Service Port
    targetPort: 80      # Container Port
    nodePort: 30081     # Port exposed externally (30000-32767 range)
